### ISSUE TITLE
Vagrant synced_folder issues

### ISSUE THREAD

**Issue by gbrennon** [willmendesneto/vagrant-frontend-mobile-box#1]
synced_folder points to "/home/willmendes/...." and do not create the desired dir.

**Comment by willmendesneto** [comment]
@gbrennon , can you edit this issue, please? You open one issue with two responsabilities and it's not so good. The synced_folder is one and server port conflict is another issue.

**Comment by gbrennon** [comment]
Issue edited ;)

**Comment by willmendesneto** [comment]
Thanks @gbrennon !

**Comment by willmendesneto** [comment]
Issue closed via https://github.com/willmendesneto/vagrant-frontend-mobile-box/pull/2
